---
  - name: ELIXIR | Add signing key
    apt_key: url=https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc state=present
    become: yes
    tags:
      - elixir

  - name: ELIXIR | Add custom repository
    apt_repository: repo="deb https://packages.erlang-solutions.com/ubuntu {{ ansible_distribution_release | lower }} contrib"  state=present
    become: yes
    tags:
      - elixir

  - name: ELIXIR | Install main package
    apt: pkg=elixir update_cache=yes state=present
    become: yes
    tags:
      - elixir
